### ISSUE TITLE
Payouts Stats API doesn't contain decimals in amount

### ISSUE THREAD

**Issue by damiandizeo** [novablockofficial/api_documentation#1]
Hi, i was starting using your API but when I request https://novablock.com/api/v1/payout/stats, noticed that the amount not contains decimals.
The response I get is:

"yesterday_amount": "1100585", but in reality yesterday amount was **0.01100585**

From where can I get the real amount with the correct decimals?

Thanks in advance.

**Comment by DaimpasK** [comment]
Sorry, the amount returned by the API is an integer and needs to be converted into the corresponding format.

https://github.com/novablockofficial/api_documentation/blob/master/README.md#unit-convert

**Comment by damiandizeo** [comment]
> Sorry, the amount returned by the API is an integer and needs to be converted into the corresponding format.
> 
> https://github.com/novablockofficial/api_documentation/blob/master/README.md#unit-convert

Thanks!! 🙂
